pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - or:
          - author=scala-steward
          - author=scala-steward[bot]
    actions:
      label:
        add:
          - dependency-update
  - name: merge scala-steward's PRs
    conditions:
      - or:
          - author=scala-steward
          - author=scala-steward[bot]
      - "#check-failure=0"
      - "#check-success>0"
      - "#check-pending=0"
    actions:
      merge:
        method: merge
