name: CI
on:
  push:
    branches:
      - "main"
      - "website" # TODO remove before merging
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Deploy the website
        #    TODO should use latest stable version instead
        run: |
          DECISIONS4S_VERSION=$(sbt -batch -error 'print decisions4s-core / version')
          cd website
          yarn deploy